import os
from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import requests, random, traceback

from persona import BASE_PERSONA
from safety import check_risk, CRISIS_MESSAGE

# ======================
# KONFIGURASI GROQ
# ======================
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
MODEL_NAME = "llama3-8b-8192"

if not GROQ_API_KEY:
    raise RuntimeError("GROQ_API_KEY belum terbaca. Cek file .env")

app = FastAPI()
app.mount("/static", StaticFiles(directory="static"), name="static")


class ChatRequest(BaseModel):
    message: str


# ======================
# BANK RESPONS
# ======================

PURE_GREETINGS = [
    "Halo.",
    "Hai.",
    "Hai, gimana?",
    "Halo, ada apa?",
    "Hai, mau ngobrol soal apa?",
    "Halo, aku di sini.",
    "Hai, silakan cerita.",
    "Halo, gimana harimu?",
    "Hai, aku denger.",
    "Halo, pelan-pelan aja.",

    "Hai, aku di sini buat dengerin.",
    "Halo, mau cerita apa hari ini?",
    "Hai, kamu nggak sendirian di sini.",
    "Halo, pelan aja, aku ada.",
    "Hai, silakan mulai dari mana aja.",
    "Halo, ambil waktumu.",
    "Hai, aku siap denger.",
    "Halo, kamu boleh cerita apa pun.",
    "Hai, aku nggak ke mana-mana.",
    "Halo, apa yang lagi kerasa?",

    "Hai, aku di sini tanpa ngejar.",
    "Halo, mau ngobrol santai atau serius?",
    "Hai, aku ikut alurnya.",
    "Halo, kamu aman cerita di sini.",
    "Hai, mulai aja dulu.",
    "Halo, tarik napas dulu juga nggak apa.",
    "Hai, aku hadir.",
    "Halo, mau mulai pelan-pelan?",
    "Hai, ceritamu penting.",
    "Halo, aku dengerin.",

     "Hai, aku ada buat nemenin.",
    "Halo, mau mulai dari mana?",
    "Hai, ceritamu aman di sini.",
    "Halo, aku siap denger.",
    "Hai, pelan juga nggak apa-apa.",
    "Halo, ambil napas dulu.",
    "Hai, aku masih di sini.",
    "Halo, kamu boleh cerita apa aja.",
    "Hai, mulai aja dulu.",
    "Halo, apa yang lagi kamu rasain?",

    "Hai, aku denger tanpa nyela.",
    "Halo, aku nggak buru-buru.",
    "Hai, kamu nggak sendirian.",
    "Halo, ceritain sebisanya.",
    "Hai, aku ikut alurnya.",
    "Halo, aku temenin.",
    "Hai, aku hadir.",
    "Halo, mau cerita pelan-pelan?",
    "Hai, nggak apa-apa kalau belum rapi.",
    "Halo, aku di sini.",

     "Hai, aku siap denger kapan pun.",
    "Halo, mau cerita sedikit dulu?",
    "Hai, kamu nggak sendirian di sini.",
    "Halo, aku temenin prosesnya.",
    "Hai, ceritain aja sebisanya.",
    "Halo, aku nggak ke mana-mana.",
    "Hai, pelan juga nggak apa.",
    "Halo, kita mulai dari yang kamu mau.",
    "Hai, aku ada buat dengerin.",
    "Halo, ambil napas dulu juga boleh.",

    "Hai, aku di sini tanpa ngejar.",
    "Halo, mau mulai sekarang?",
    "Hai, aku ikut alurnya.",
    "Halo, ceritamu aman.",
    "Hai, aku siap nyimak.",
    "Halo, nggak harus rapi.",
    "Hai, apa pun yang kamu rasain valid.",
    "Halo, kita pelan-pelan.",
    "Hai, aku hadir sepenuhnya.",
    "Halo, kamu boleh mulai kapan aja.",

    "Hai, aku masih di sini.",
    "Halo, mau mulai dari mana?",
    "Hai, ceritamu boleh berantakan.",
    "Halo, aku temenin tanpa buru-buru.",
    "Hai, kamu aman cerita di sini.",
    "Halo, aku nggak nge-judge.",
    "Hai, kamu boleh pelan.",
    "Halo, kita ngobrol aja.",
    "Hai, aku denger sepenuhnya.",
    "Halo, aku siap nyimak.",

    "Hai, kamu nggak harus kuat di sini.",
    "Halo, kamu boleh jujur.",
    "Hai, aku ikut ritmemu.",
    "Halo, kita santai aja.",
    "Hai, aku ada buat denger.",
    "Halo, mau cerita sedikit?",
    "Hai, pelan juga jalan.",
    "Halo, aku hadir.",
    "Hai, ceritain kalau mau.",
    "Halo, aku temenin."
]


SAFE_FALLBACK = [
    "Boleh jelasin dikit lagi?",
    "Aku pengin ngerti lebih jelas.",
    "Coba ceritain pelan-pelan aja.",
    "Kayaknya aku belum nangkep sepenuhnya.",
    "Bagian mana yang paling berat menurutmu?",
    "Ini kejadiannya baru atau udah lama?",
    "Kalau kamu mau, ceritain dari awal juga nggak apa-apa.",
    "Aku masih ngikutin, lanjut aja.",
    "Ambil waktumu, aku denger.",
    "Kalau bingung mulai dari mana, ambil bagian yang paling kerasa dulu.",

     "Aku pengin pastiin aku nangkep dengan benar.",
    "Bagian mana yang paling kerasa sekarang?",
    "Kalau diringkas satu kalimat, apa intinya?",
    "Aku boleh minta contoh kecilnya?",
    "Ini lebih ke perasaan atau kejadian?",
    "Yang paling bikin kepikiran apa?",
    "Kalau diulang, bagian mana yang pengin ditekanin?",
    "Aku belum sepenuhnya kebayang, boleh dijelasin dikit?",
    "Apa ini kejadian tunggal atau berulang?",
    "Kapan terakhir kali ini kerasa berat?",

    "Aku pengin ngerti tanpa nyela.",
    "Kamu pengin dipahami atau cuma ditemani?",
    "Kalau mau, kita bisa urut satu-satu.",
    "Bagian ini terasa campur aduk ya?",
    "Apa ada hal yang belum kamu sebut?",
    "Kalau kamu pause sebentar juga nggak apa.",
    "Aku masih ngikutin ceritamu.",
    "Aku belum nyimpulin apa pun.",
    "Aku pengin denger versimu.",
    "Ceritain sebisanya aja.",

    "Ini topik yang sensitif ya?",
    "Aku pengin nangkep nadanya.",
    "Bagian ini rasanya berat ya?",
    "Kalau diulang pelan-pelan, gimana ceritanya?",
    "Apa ini masih kejadian sekarang?",
    "Apa ini sering kepikiran belakangan?",
    "Kalau kamu pilih satu bagian, yang mana?",
    "Aku belum mau narik kesimpulan.",
    "Aku denger dulu.",
    "Lanjut kapan pun kamu siap.",

     "Aku pengin ngerti tanpa maksa.",
    "Bagian ini rasanya penting ya?",
    "Kalau kamu pilih satu hal, apa itu?",
    "Apa ini bikin kamu kepikiran terus?",
    "Apa ini kejadian lama yang keangkat lagi?",
    "Aku pengin nangkep perasaan di balik ceritanya.",
    "Kalau disederhanakan, intinya apa?",
    "Apa ada yang belum sempat kamu ucapin?",
    "Bagian mana yang paling nyantol di pikiran?",
    "Aku masih nyimak.",

    "Kalau kamu berhenti sebentar juga nggak apa.",
    "Aku nggak ngejar jawaban.",
    "Kita bisa pelan-pelan.",
    "Apa ini lebih ke capek atau sedih?",
    "Apa ini bikin kamu ngerasa sendirian?",
    "Kalau mau loncat ke bagian akhir juga nggak apa.",
    "Aku pengin denger versi kamu.",
    "Nggak harus lengkap.",
    "Aku belum nyimpulin apa pun.",
    "Lanjut aja kalau siap.",

    "Bagian ini kayaknya berat.",
    "Aku pengin ngerti sudut pandangmu.",
    "Kalau diulang, bagian mana yang paling kerasa?",
    "Ini masih kejadian sekarang?",
    "Apa ini sering muncul belakangan?",
    "Aku dengerin dulu.",
    "Aku di sini buat nangkep, bukan menilai.",
    "Kalau kamu mau diam sebentar juga nggak apa.",
    "Aku masih di sini.",
    "Ambil waktumu.",

    "Aku pengin ngerti perasaan di balik ceritanya.",
    "Apa bagian ini yang paling bikin berat?",
    "Apa ini sering kepikiran belakangan?",
    "Apa ada hal yang belum sempat kamu ceritain?",
    "Kalau kamu pilih satu kata buat jelasin, apa itu?",
    "Apa ini bikin kamu ngerasa sendirian?",
    "Aku pengin denger versi kamu sepenuhnya.",
    "Kalau mau mulai dari tengah cerita juga nggak apa.",
    "Bagian mana yang paling ngena di hati?",
    "Aku masih di sini.",

    "Kalau kamu berhenti sebentar, aku nunggu.",
    "Aku nggak buru-buru minta jawaban.",
    "Apa ini lebih ke capek atau lebih ke sedih?",
    "Apa ini kejadian lama yang keangkat lagi?",
    "Apa yang paling kamu tahan selama ini?",
    "Aku pengin nangkep, bukan nyimpulin.",
    "Kita bisa bongkar pelan-pelan.",
    "Kalau kamu bingung, itu juga nggak apa.",
    "Aku denger tanpa nyela.",
    "Ambil waktu yang kamu butuhin.",

    "Bagian ini kayaknya berat buat kamu.",
    "Aku pengin ngerti dari sudut pandangmu.",
    "Apa ini bikin kamu mikir terus?",
    "Kalau kamu ceritain ke diri sendiri, kamu bakal bilang apa?",
    "Apa ada rasa yang belum sempat keluar?",
    "Aku nggak ngejar solusi.",
    "Aku temenin dulu.",
    "Kalau mau diam sebentar juga aman.",
    "Aku masih nyimak.",
    "Lanjut kapan pun kamu siap.",

    "Apa perasaan yang paling kerasa sekarang?",
    "Apa ini lebih ke lelah atau lebih ke sedih?",
    "Apa bagian ini yang paling susah kamu ceritain?",
    "Kalau kamu jujur ke diri sendiri, apa yang kamu rasain?",
    "Apa yang paling kamu tahan belakangan ini?",
    "Apa ini sering muncul pas kamu sendirian?",
    "Apa ada hal kecil yang sebenernya berat?",
    "Kalau diringkas, ini rasanya kayak apa?",
    "Aku pengin ngerti pelan-pelan.",
    "Kita nggak perlu buru-buru.",

    "Apa ini bikin kamu ngerasa sendirian?",
    "Apa kamu ngerasa harus kuat terus?",
    "Apa ada rasa yang belum sempat keluar?",
    "Apa ini capek yang lama?",
    "Apa kamu ngerasa ketahan?",
    "Aku pengin denger tanpa motong.",
    "Kalau mau berhenti sebentar, aman.",
    "Aku masih di sini.",
    "Lanjut kapan pun kamu siap.",
    "Aku temenin prosesnya.",

    "Apa ini kejadian lama yang keangkat lagi?",
    "Apa ada hal yang belum selesai di hati?",
    "Apa kamu lagi ngerasa kosong?",
    "Apa yang paling bikin kamu mikir?",
    "Aku pengin nangkep maknanya.",
    "Kita bisa urut pelan-pelan.",
    "Nggak harus jelas sekarang.",
    "Aku nggak ngejar jawaban.",
    "Aku nyimak.",
    "Ambil waktumu.",

    "Apa kamu ngerasa capek tapi nggak tahu kenapa?",
    "Apa ada bagian dari ini yang belum pernah kamu ceritain ke siapa pun?",
    "Apa kamu lagi ngerasa sendirian walau nggak sendiri?",
    "Apa ini bikin kamu ngerasa kehabisan tenaga?",
    "Apa kamu ngerasa harus nahan diri terus?",
    "Apa kamu ngerasa nggak punya ruang buat jatuh?",
    "Apa kamu lagi ngerasa kosong tapi penuh di kepala?",
    "Apa kamu ngerasa nggak didengerin selama ini?",
    "Apa ini perasaan yang sering kamu tekan?",
    "Apa ini capek yang udah lama numpuk?",

    "Kalau kamu berhenti sebentar, apa yang kamu takutin?",
    "Kalau kamu jujur, bagian mana yang paling melelahkan?",
    "Apa kamu ngerasa harus kuat sendirian?",
    "Apa ini bikin kamu ragu sama diri sendiri?",
    "Apa kamu lagi ngerasa kehilangan arah?",
    "Apa ada perasaan yang belum sempat kamu akui?",
    "Apa kamu lagi di fase bertahan?",
    "Apa ini lebih berat di hati atau di pikiran?",
    "Apa kamu ngerasa ditinggal di situasi ini?",
    "Apa kamu ngerasa nggak cukup apa adanya?",

    "Kita bisa pelan, nggak perlu beres sekarang.",
    "Aku di sini buat denger, bukan nyuruh.",
    "Nggak apa-apa kalau belum nemu kata-katanya.",
    "Kalau berat, kita potong kecil-kecil.",
    "Aku nggak butuh jawaban cepat.",
    "Aku pengin ngerti versimu.",
    "Kita ikutin rasanya dulu.",
    "Nggak apa-apa kalau ceritanya lompat-lompat.",
    "Aku tetap dengerin.",
    "Ambil napas dulu juga boleh."
]


# ==================================================
# EMPATHY BANK 
# ==================================================

EMPATHY_BANK = {}

EMPATHY_BANK["capek"] = [
    "Capeknya kayak nggak ada ujung ya.",
    "Kayaknya kamu udah lama nggak bener-bener istirahat.",
    "Capek yang bikin bangun tidur pun masih berat.",
    "Kelihatannya kamu jalan terus tanpa jeda.",
    "Capek yang pelan tapi nggerogotin.",
    "Capek karena terlalu banyak mikir.",
    "Capek karena terlalu sering menahan diri.",
    "Capek yang nggak kelihatan tapi kerasa banget.",
    "Capek yang bikin hal kecil jadi berat.",
    "Capek yang numpuk dari banyak hal kecil.",

    "Kayaknya kamu kelelahan tapi masih maksa kuat.",
    "Capek karena tanggung jawab yang nggak berhenti.",
    "Capek yang datang bukan dari satu hal aja.",
    "Capek karena jarang didengerin.",
    "Capek karena sering ngalah.",
    "Capek karena ngerasa harus selalu bisa.",
    "Capek yang bikin pengin berhenti sebentar.",
    "Capek yang bikin fokus buyar.",
    "Capek yang bikin emosi gampang naik.",
    "Capek yang bikin pengin menghilang sebentar.",

    "Capeknya bukan cuma di badan, tapi juga di kepala.",
    "Capek yang bikin pengin diem.",
    "Capek karena ngerasa sendirian.",
    "Capek karena terus mikirin orang lain.",
    "Capek karena nggak punya ruang sendiri.",
    "Capek karena harus kuat di depan orang.",
    "Capek karena jarang diprioritaskan.",
    "Capek karena ngerasa dikejar waktu.",
    "Capek karena semuanya terasa urgent.",
    "Capek yang bikin susah menikmati apa pun.",
    "Capek yang bikin semuanya terasa lambat.",
    "Capek yang bikin pengin berhenti mikir.",
    "Capek karena terlalu sering menyesuaikan diri.",
    "Capek karena harus kelihatan baik-baik aja.",
    "Capek karena ngerasa nggak boleh jatuh.",
    "Capek karena terlalu banyak tuntutan.",
    "Capek karena jarang diapresiasi.",
    "Capek karena harus jadi sandaran orang lain.",
    "Capek yang bikin motivasi turun.",
    "Capek yang bikin hal kecil terasa berat.",

    "Capek karena kamu jarang mikirin diri sendiri.",
    "Capek karena terus ngasih tanpa diisi ulang.",
    "Capek yang bikin kamu ngerasa kosong.",
    "Capek karena ekspektasi yang tinggi.",
    "Capek karena pengin semuanya beres.",
    "Capek yang bikin kamu pengin sendiri.",
    "Capek karena nggak punya ruang ngeluh.",
    "Capek karena harus kuat sendirian.",
    "Capek karena nggak tahu harus istirahat kapan.",
    "Capek yang bikin kamu mempertanyakan semuanya.",

    "Capek yang datang pelan-pelan tapi konsisten.",
    "Capek yang bikin semangat naik turun.",
    "Capek karena hidup kerasa berat akhir-akhir ini.",
    "Capek yang bikin kamu gampang sensitif.",
    "Capek yang bikin pengin tidur lama.",
    "Capek karena rutinitas yang monoton.",
    "Capek karena ngerasa terjebak.",
    "Capek karena pengin berubah tapi belum bisa.",
    "Capek yang bikin kamu ngerasa tertinggal.",
    "Capek karena semuanya terasa tanggung.",
    "Capek yang bikin kamu kehilangan antusiasme.",
    "Capek yang bikin hari terasa panjang.",
    "Capek karena harus konsisten terus.",
    "Capek karena jarang dapet jeda.",
    "Capek yang bikin kamu pengin menghilang sebentar.",
    "Capek karena terlalu sering mengalah.",
    "Capek karena tanggung jawab nggak berkurang.",
    "Capek karena ngerasa sendirian ngejalaninnya.",
    "Capek yang bikin kamu gampang menyerah.",
    "Capek yang bikin fokus berantakan.",

    "Capek karena hidup terasa repetitif.",
    "Capek karena harus tampil stabil.",
    "Capek karena jarang ditanya kabarnya.",
    "Capek karena selalu dituntut ngerti.",
    "Capek yang bikin kamu ngerasa nggak berkembang.",
    "Capek karena terus dibandingkan.",
    "Capek karena target terus naik.",
    "Capek karena istirahat pun kepikiran.",
    "Capek karena pengin berhenti tapi nggak bisa.",
    "Capek yang bikin kamu ngerasa hambar.",

    "Capek karena jarang merasa cukup.",
    "Capek karena hidup terasa berat belakangan ini.",
    "Capek yang bikin kamu susah menikmati hal kecil.",
    "Capek karena semua terasa mendesak.",
    "Capek karena pengin semuanya selesai.",
    "Capek karena harus ngejar waktu.",
    "Capek yang bikin kamu ngerasa tertekan.",
    "Capek karena nggak tahu harus ngadu ke siapa.",
    "Capek karena selalu ada yang harus dipikirin.",
    "Capek yang bikin kamu pengin istirahat dari segalanya.",

    # kerja
    "Capek karena kerjaan nggak ada habisnya.",
    "Capek karena target terus nambah.",
    "Capek karena kerja keras tapi kurang diapresiasi.",
    "Capek karena harus profesional terus.",
    "Capek karena pulang kerja masih mikirin kerjaan.",
    "Capek karena tuntutan lebih besar dari kemampuan saat ini.",
    "Capek karena ekspektasi kantor nggak realistis.",
    "Capek karena harus multitasking terus.",
    "Capek karena jam kerja nggak jelas.",
    "Capek karena kerja tapi nggak merasa berkembang.",
# relasi
    "Capek karena harus jaga perasaan orang lain.",
    "Capek karena selalu jadi pihak yang ngerti.",
    "Capek karena hubungan nggak seimbang.",
    "Capek karena komunikasi sering mentok.",
    "Capek karena terlalu sering mengalah.",
    "Capek karena merasa sendirian dalam hubungan.",
    "Capek karena harus jelasin hal yang sama berulang kali.",
    "Capek karena berharap tapi sering kecewa.",
    "Capek karena ngerasa nggak didengar.",
    "Capek karena hubungan berubah tapi kamu masih bertahan.",

    # keluarga
    "Capek karena tanggung jawab keluarga berat.",
    "Capek karena harus kuat di rumah.",
    "Capek karena jarang dipahami keluarga sendiri.",
    "Capek karena beban keluarga nggak bisa dibagi.",
    "Capek karena tuntutan keluarga terus ada.",
    "Capek karena harus dewasa lebih cepat.",
    "Capek karena peran di keluarga terlalu besar.",
    "Capek karena jarang ditanya kabarnya.",
    "Capek karena harus menahan perasaan di rumah.",
    "Capek karena rumah nggak selalu jadi tempat istirahat.",

    # eksistensial
    "Capek karena hidup terasa monoton.",
    "Capek karena mempertanyakan arah hidup.",
    "Capek karena ngerasa jalan di tempat.",
    "Capek karena merasa tertinggal.",
    "Capek karena hidup terasa berat tanpa alasan jelas.",
    "Capek karena kehilangan makna.",
    "Capek karena ngerasa harus terus bertahan.",
    "Capek karena merasa nggak cukup.",
    "Capek karena membandingkan diri dengan orang lain.",
    "Capek karena masa depan terasa kabur.",

"Capeknya kerasa ya.",
    "Kayaknya berat banget.",
    "Ini bukan capek biasa.",
    "Capek yang numpuk.",
    "Capek tapi masih jalan.",
    "Capek tapi nggak bisa berhenti.",
    "Capek tapi tetap maksa.",
    "Capeknya dalam.",
    "Capek yang susah dijelasin.",
    "Capek yang diem-diem.",

    "Kelihatan kamu nahan.",
    "Kelihatan kamu kelelahan.",
    "Kelihatan kamu udah mentok.",
    "Kelihatan kamu berusaha.",
    "Kelihatan kamu masih bertahan.",
    "Kelihatan kamu nggak baik-baik aja.",
    "Kelihatan kamu kuat tapi lelah.",
    "Kelihatan kamu kehabisan energi.",
    "Kelihatan kamu pengin istirahat.",
    "Kelihatan kamu lagi berat.",

    "Ini capek yang lama.",
    "Ini capek yang tertahan.",
    "Ini capek yang pelan-pelan.",
    "Ini capek yang ngendap.",
    "Ini capek yang nggak kelihatan.",
    "Ini capek yang bikin sunyi.",
    "Ini capek yang bikin kosong.",
    "Ini capek yang bikin lambat.",
    "Ini capek yang nempel.",
    "Ini capek yang numpang hidup.",
]

EMPATHY_BANK["sedih"] = [
    "Sedihnya kerasa dalam ya.",
    "Kayaknya ini bukan sedih yang ringan.",
    "Sedih yang datang diam-diam.",
    "Sedih yang susah dijelasin ke orang lain.",
    "Sedih yang bikin dada terasa sesak.",
    "Sedih yang bikin pengin menarik diri.",
    "Sedih yang bikin dunia kerasa lebih sepi.",
    "Sedih yang datang tanpa alasan jelas.",
    "Sedih yang nggak bisa langsung ilang.",
    "Sedih yang bikin kamu ngerasa kecil.",

    "Kelihatannya kamu lagi nyimpen rasa.",
    "Sedih yang bikin kamu banyak mikir sendiri.",
    "Sedih karena ekspektasi nggak ketemu kenyataan.",
    "Sedih karena ngerasa nggak dipahami.",
    "Sedih karena kehilangan sesuatu yang penting.",
    "Sedih karena ngerasa gagal.",
    "Sedih karena capek berharap.",
    "Sedih yang bikin hati berat.",
    "Sedih yang bikin susah tidur.",
    "Sedih yang bikin pengin menangis tapi tertahan.",

    "Sedih yang nggak kelihatan dari luar.",
    "Sedih yang kamu pendam lama.",
    "Sedih yang datang setelah kamu berusaha.",
    "Sedih karena merasa sendirian di situasi ini.",
    "Sedih karena ngerasa nggak cukup.",
    "Sedih karena merasa dilupakan.",
    "Sedih karena kenyataan pahit.",
    "Sedih yang bikin kamu diam lebih lama.",
    "Sedih yang bikin senyum terasa berat.",
    "Sedih yang bikin waktu jalan lebih lambat.",
     "Sedih yang kamu simpan sendiri.",
    "Sedih yang datang pas lagi sendirian.",
    "Sedih yang bikin pengin diam.",
    "Sedih yang bikin napas terasa berat.",
    "Sedih karena harapan yang nggak kejadian.",
    "Sedih karena merasa nggak dianggap.",
    "Sedih karena kehilangan arah.",
    "Sedih yang bikin kamu ngerasa rapuh.",
    "Sedih yang bikin dunia kerasa sunyi.",
    "Sedih karena ngerasa gagal.",

    "Sedih yang datang setelah berusaha keras.",
    "Sedih karena ngerasa nggak dipilih.",
    "Sedih karena terlalu berharap.",
    "Sedih yang bikin kamu mempertanyakan diri sendiri.",
    "Sedih karena merasa tertinggal.",
    "Sedih yang bikin kamu menarik diri.",
    "Sedih yang bikin hal kecil terasa besar.",
    "Sedih karena merasa nggak cukup.",
    "Sedih karena ngerasa nggak dipahami.",
    "Sedih yang bikin kamu capek emosional.",

    "Sedih karena kenyataan nggak sesuai rencana.",
    "Sedih karena harus melepaskan.",
    "Sedih karena ngerasa sendirian di keramaian.",
    "Sedih yang datang tiba-tiba.",
    "Sedih yang susah dijelasin ke siapa pun.",
    "Sedih yang bikin senyum terasa palsu.",
    "Sedih yang bikin kamu lebih pendiam.",
    "Sedih karena merasa nggak didengar.",
    "Sedih yang bikin kamu ngerasa jauh dari diri sendiri.",
    "Sedih yang bikin kamu kehilangan semangat.",
    "Sedih karena realita nggak seindah bayangan.",
    "Sedih karena ngerasa ditinggal.",
    "Sedih karena usaha belum kelihatan hasilnya.",
    "Sedih yang bikin kamu ngerasa kecil.",
    "Sedih karena ngerasa nggak diprioritaskan.",
    "Sedih karena kehilangan sesuatu yang penting.",
    "Sedih karena hubungan berubah.",
    "Sedih karena harapan pelan-pelan pudar.",
    "Sedih karena ngerasa nggak nyampe.",
    "Sedih yang bikin kamu lebih pendiam dari biasanya.",

    "Sedih karena nggak tahu harus ngapain.",
    "Sedih karena merasa nggak cocok di tempat ini.",
    "Sedih yang datang tanpa alasan jelas.",
    "Sedih karena merasa tertolak.",
    "Sedih karena ngerasa gagal memenuhi ekspektasi.",
    "Sedih karena terlalu banyak mengalah.",
    "Sedih karena ngerasa nggak dihargai.",
    "Sedih yang bikin kamu pengin menyendiri.",
    "Sedih karena ngerasa kosong.",
    "Sedih yang bikin kamu kehilangan arah.",

    "Sedih karena hidup nggak berjalan sesuai rencana.",
    "Sedih karena merasa sendirian walau ramai.",
    "Sedih yang bikin senyum terasa berat.",
    "Sedih karena ngerasa jauh dari diri sendiri.",
    "Sedih karena kenyataan terlalu keras.",
    "Sedih karena harus menerima hal yang nggak diinginkan.",
    "Sedih yang bikin kamu capek secara emosional.",
    "Sedih karena nggak tahu harus berharap apa.",
    "Sedih yang bikin kamu ngerasa rapuh.",
    "Sedih yang nggak butuh solusi cepat.",
    # kerja
    "Sedih karena usaha di kerjaan nggak dihargai.",
    "Sedih karena ngerasa nggak cocok sama kerjaan sekarang.",
    "Sedih karena mimpi kerja belum kesampaian.",
    "Sedih karena kehilangan semangat kerja.",
    "Sedih karena lingkungan kerja bikin tertekan.",
    "Sedih karena harus bertahan di tempat yang nggak sehat.",
    "Sedih karena performa turun.",
    "Sedih karena merasa gagal secara profesional.",
    "Sedih karena pilihan karier terasa salah.",
    "Sedih karena kerja keras belum berbuah.",

    # relasi
    "Sedih karena hubungan berubah.",
    "Sedih karena merasa nggak lagi penting.",
    "Sedih karena kepercayaan terganggu.",
    "Sedih karena kehilangan kedekatan.",
    "Sedih karena ngerasa sendirian dalam hubungan.",
    "Sedih karena harapan nggak terpenuhi.",
    "Sedih karena harus melepaskan.",
    "Sedih karena cinta nggak sejalan.",
    "Sedih karena komunikasi terasa dingin.",
    "Sedih karena masih peduli tapi lelah.",

    # keluarga
    "Sedih karena nggak dimengerti keluarga.",
    "Sedih karena jarak emosional di rumah.",
    "Sedih karena konflik keluarga berlarut-larut.",
    "Sedih karena peran keluarga berubah.",
    "Sedih karena kehilangan figur penting.",
    "Sedih karena rumah terasa asing.",
    "Sedih karena harus menahan perasaan demi keluarga.",
    "Sedih karena ekspektasi keluarga berat.",
    "Sedih karena merasa sendirian di rumah sendiri.",
    "Sedih karena nggak bisa jadi diri sendiri.",

    # eksistensial
    "Sedih karena hidup terasa kosong.",
    "Sedih karena kehilangan arah.",
    "Sedih karena harapan memudar.",
    "Sedih karena masa depan terasa menakutkan.",
    "Sedih karena ngerasa tertinggal.",
    "Sedih karena mimpi berubah.",
    "Sedih karena realita nggak ramah.",
    "Sedih karena hidup nggak sesuai bayangan.",
    "Sedih karena ngerasa gagal sebagai diri sendiri.",
    "Sedih yang nggak tahu harus diapain.",
    "Sedihnya kerasa.",
    "Sedihnya dalem.",
    "Ini sedih yang berat.",
    "Ini sedih yang nggak ribut.",
    "Ini sedih yang sunyi.",
    "Ini sedih yang dipendem.",
    "Ini sedih yang lama.",
    "Ini sedih yang nyangkut.",
    "Ini sedih yang bikin kosong.",
    "Ini sedih yang nggak kelihatan.",

    "Kelihatan kamu lagi sedih.",
    "Kelihatan kamu lagi patah.",
    "Kelihatan kamu lagi jatuh.",
    "Kelihatan kamu lagi kehilangan.",
    "Kelihatan kamu lagi berat.",
    "Kelihatan kamu lagi nahan air mata.",
    "Kelihatan kamu lagi hancur pelan-pelan.",
    "Kelihatan kamu lagi diam tapi sakit.",
    "Kelihatan kamu lagi nyoba kuat.",
    "Kelihatan kamu lagi rapuh.",

    "Sedihnya nggak perlu dijelasin.",
    "Sedihnya cukup kamu rasain.",
    "Sedihnya nggak harus cepet ilang.",
    "Sedihnya boleh ada.",
    "Sedihnya valid.",
    "Sedihnya manusiawi.",
    "Sedihnya wajar.",
    "Sedihnya punya tempat.",
    "Sedihnya nggak salah.",
    "Sedihnya boleh pelan.",
]

EMPATHY_BANK["bingung"] = [
    "Kayaknya kepalamu lagi penuh ya.",
    "Bingung karena terlalu banyak pilihan.",
    "Bingung karena semua opsi terasa berat.",
    "Bingung karena nggak ada jawaban yang jelas.",
    "Bingung karena takut salah langkah.",
    "Bingung karena mikir terlalu jauh.",
    "Bingung yang bikin susah fokus.",
    "Bingung yang bikin ragu sama diri sendiri.",
    "Bingung karena pengin yang terbaik.",
    "Bingung karena semuanya terasa abu-abu.",

    "Kayaknya kamu lagi di persimpangan.",
    "Bingung antara nurutin logika atau perasaan.",
    "Bingung karena situasinya nggak sederhana.",
    "Bingung karena informasinya bertabrakan.",
    "Bingung karena terlalu banyak pertimbangan.",
    "Bingung yang bikin capek sendiri.",
    "Bingung karena nggak ada pegangan jelas.",
    "Bingung yang bikin muter-muter di kepala.",
    "Bingung karena takut nyesel nanti.",
    "Bingung karena ngerasa sendirian mutusin.",

    "Bingung tapi tetap pengin maju.",
    "Bingung karena nggak ada pilihan ideal.",
    "Bingung karena semua terasa berisiko.",
    "Bingung karena waktu terus jalan.",
    "Bingung karena tekanan dari sekitar.",
    "Bingung karena ekspektasi orang lain.",
    "Bingung karena pengin berubah tapi takut.",
    "Bingung karena arah hidup kerasa kabur.",
    "Bingung yang bikin kamu overthinking.",
    "Bingung tapi nggak pengin nyerah.",
    "Bingung karena semua terasa setengah-setengah.",
    "Bingung karena nggak tahu harus mulai dari mana.",
    "Bingung karena pilihan sama-sama berat.",
    "Bingung karena pengin cepat jelas tapi belum bisa.",
    "Bingung yang bikin kamu overthinking.",
    "Bingung karena takut ambil keputusan.",
    "Bingung karena situasinya berubah terus.",
    "Bingung karena ekspektasi bertabrakan.",
    "Bingung karena terlalu banyak pendapat.",
    "Bingung yang bikin kamu ragu sama diri sendiri.",

    "Bingung antara bertahan atau berubah.",
    "Bingung karena nggak ada jawaban hitam-putih.",
    "Bingung karena pengin aman tapi juga berkembang.",
    "Bingung karena ngerasa ditarik dari banyak arah.",
    "Bingung yang bikin kamu capek mikir.",
    "Bingung karena semuanya terasa mendesak.",
    "Bingung karena nggak pengin salah langkah.",
    "Bingung karena takut konsekuensi.",
    "Bingung karena pengin semua orang senang.",
    "Bingung karena kamu peduli terlalu banyak.",

    "Bingung karena belum nemu pijakan.",
    "Bingung karena masa depan terasa kabur.",
    "Bingung karena terlalu banyak kemungkinan.",
    "Bingung karena realita nggak sederhana.",
    "Bingung yang bikin kamu ngerasa stuck.",
    "Bingung karena pengin yakin tapi ragu.",
    "Bingung karena tekanan waktu.",
    "Bingung karena ngerasa sendirian mutusin.",
    "Bingung karena takut nyesel.",
    "Bingung tapi masih pengin jalan.",
    "Bingung karena pilihan sama-sama ada risikonya.",
    "Bingung karena pengin aman tapi juga pengin maju.",
    "Bingung karena semuanya terasa abu-abu.",
    "Bingung karena nggak ada jawaban pasti.",
    "Bingung karena terlalu banyak pertimbangan.",
    "Bingung karena situasinya kompleks.",
    "Bingung yang bikin kamu ragu melangkah.",
    "Bingung karena takut salah ambil keputusan.",
    "Bingung karena pengin cepat selesai.",
    "Bingung karena tekanan dari berbagai arah.",

    "Bingung karena ngerasa harus milih sekarang.",
    "Bingung karena konsekuensinya berat.",
    "Bingung karena pendapat orang beda-beda.",
    "Bingung karena nggak pengin nyakitin siapa pun.",
    "Bingung karena kamu peduli sama banyak hal.",
    "Bingung yang bikin kamu bolak-balik mikir.",
    "Bingung karena nggak ada panduan jelas.",
    "Bingung karena ngerasa belum siap.",
    "Bingung karena takut nyesel.",
    "Bingung yang bikin kamu ngerasa stuck.",

    "Bingung karena hidup lagi di fase transisi.",
    "Bingung karena arah belum kebaca.",
    "Bingung karena rencana berubah.",
    "Bingung karena ekspektasi nggak realistis.",
    "Bingung karena pengin yakin tapi ragu.",
    "Bingung karena terlalu banyak kemungkinan.",
    "Bingung karena nggak ada waktu mikir tenang.",
    "Bingung karena semuanya terasa penting.",
    "Bingung karena pengin benar tapi manusiawi.",
    "Bingung tapi tetap pengin melangkah.",
    
    # kerja
    "Bingung mau lanjut di kerjaan ini atau nggak.",
    "Bingung milih bertahan atau pindah.",
    "Bingung karena karier terasa mentok.",
    "Bingung karena nggak tahu langkah selanjutnya.",
    "Bingung karena pilihan kerjaan terbatas.",
    "Bingung karena takut salah ambil keputusan karier.",
    "Bingung karena minat dan realita beda.",
    "Bingung karena tuntutan kerja berubah.",
    "Bingung karena arah karier nggak jelas.",
    "Bingung karena ekspektasi diri tinggi.",

    # relasi
    "Bingung harus bertahan atau pergi.",
    "Bingung karena perasaan campur aduk.",
    "Bingung karena masih sayang tapi capek.",
    "Bingung karena sinyal dari dia nggak jelas.",
    "Bingung karena hubungan di fase abu-abu.",
    "Bingung karena takut nyakitin.",
    "Bingung karena komunikasi nggak nyambung.",
    "Bingung karena pengin berubah tapi ragu.",
    "Bingung karena hubungan stagnan.",
    "Bingung karena nggak tahu maunya apa.",

    # keluarga
    "Bingung menghadapi ekspektasi keluarga.",
    "Bingung antara nurut atau jujur sama diri sendiri.",
    "Bingung karena peran di keluarga berubah.",
    "Bingung karena konflik keluarga rumit.",
    "Bingung karena harus milih prioritas.",
    "Bingung karena pengin mandiri tapi terikat.",
    "Bingung karena perbedaan nilai.",
    "Bingung karena tekanan keluarga.",
    "Bingung karena harus dewasa cepat.",
    "Bingung karena nggak ada jawaban pasti.",

    # eksistensial
    "Bingung soal tujuan hidup.",
    "Bingung mau jadi apa.",
    "Bingung karena hidup berubah cepat.",
    "Bingung karena masa depan nggak jelas.",
    "Bingung karena pilihan terlalu banyak.",
    "Bingung karena takut salah jalan.",
    "Bingung karena ngerasa kosong.",
    "Bingung karena kehilangan arah.",
    "Bingung karena hidup di persimpangan.",
    "Bingung tapi tetap pengin melangkah.",
    "Bingungnya kerasa.",
    "Ini bingung yang penuh.",
    "Ini bingung yang muter.",
    "Ini bingung yang bikin diam.",
    "Ini bingung yang bikin ragu.",
    "Ini bingung yang bikin berhenti.",
    "Ini bingung yang bikin mikir terus.",
    "Ini bingung yang berat.",
    "Ini bingung yang capek.",
    "Ini bingung yang panjang.",

    "Kelihatan kamu lagi bingung.",
    "Kelihatan kamu lagi nyari.",
    "Kelihatan kamu lagi ragu.",
    "Kelihatan kamu lagi di tengah.",
    "Kelihatan kamu lagi di persimpangan.",
    "Kelihatan kamu lagi nggak yakin.",
    "Kelihatan kamu lagi mikir keras.",
    "Kelihatan kamu lagi kelelahan mikir.",
    "Kelihatan kamu lagi cari pegangan.",
    "Kelihatan kamu lagi kosong.",

    "Bingung nggak selalu buruk.",
    "Bingung tanda mikir.",
    "Bingung tanda peduli.",
    "Bingung tanda nyari arah.",
    "Bingung tanda kamu hidup.",
    "Bingung tanda kamu sadar.",
    "Bingung tanda kamu nggak asal jalan.",
    "Bingung tanda kamu berhenti sebentar.",
    "Bingung tanda kamu reflektif.",
    "Bingung tanda kamu manusia.",
]

EMPATHY_BANK["netral"] = [
    "Aku di sini.",
    "Aku dengerin.",
    "Pelan aja nggak apa-apa.",
    "Ceritain sebisanya.",
    "Nggak harus rapi.",
    "Ambil waktumu.",
    "Aku ngikutin ceritamu.",
    "Silakan lanjut.",
    "Aku masih di sini.",
    "Terus aja kalau mau.",

    "Aku temenin.",
    "Nggak perlu buru-buru.",
    "Apa pun yang pengin kamu ceritain, silakan.",
    "Aku siap denger.",
    "Lanjut kapan pun kamu siap.",
    "Aku nggak ke mana-mana.",
    "Napas dulu juga nggak apa-apa.",
    "Aku hadir di sini.",
    "Aku nyimak.",
    "Ceritamu aman di sini.",
     "Aku tetap di sini.",
    "Nggak apa-apa kalau belum rapi.",
    "Ceritain sedikit-sedikit juga nggak apa.",
    "Aku dengerin tanpa ngejar.",
    "Lanjut kapan pun kamu siap.",
    "Aku nggak maksa.",
    "Kita pelan aja.",
    "Aku temenin prosesnya.",
    "Kamu nggak sendirian di sini.",
    "Aku masih nyimak.",

    "Silakan lanjut.",
    "Ambil napas dulu juga boleh.",
    "Aku ikut alurnya.",
    "Aku hadir di sini.",
    "Ceritamu aman.",
    "Aku nggak buru-buru.",
    "Aku ngikutin ceritanya.",
    "Pelan-pelan juga jalan.",
    "Aku siap denger.",
    "Aku temenin tanpa syarat.",
    "Aku masih di sini.",
    "Kita bisa lanjut pelan.",
    "Aku dengerin.",
    "Ambil waktumu.",
    "Nggak usah buru-buru.",
    "Aku temenin.",
    "Silakan lanjut kapan pun.",
    "Aku ikut alurnya.",
    "Aku hadir.",
    "Aku ngikutin.",

    "Nggak apa-apa kalau belum jelas.",
    "Ceritamu aman di sini.",
    "Aku nggak ke mana-mana.",
    "Pelan juga nggak masalah.",
    "Aku siap denger.",
    "Aku di sini tanpa menilai.",
    "Lanjut aja.",
    "Aku nyimak.",
    "Ambil napas dulu juga boleh.",
    "Aku tetep dengerin.",
    "Aku di sini.",
    "Aku denger.",
    "Aku ngikutin.",
    "Aku masih di sini.",
    "Aku nggak ke mana-mana.",
    "Ambil waktumu.",
    "Pelan aja.",
    "Nggak apa-apa.",
    "Lanjut kalau siap.",
    "Aku tunggu.",

    "Kita pelan-pelan.",
    "Nggak usah buru-buru.",
    "Tarik napas dulu.",
    "Kita satu-satu.",
    "Aku temenin.",
    "Kita hadapi bareng.",
    "Kita obrolin.",
    "Aku ada.",
    "Aku dengerin.",
    "Aku hadir.",
]

# ======================
# PHILOSOPHY BANK
# ======================

PHILOSOPHY_BANK = {
    "capek": [
        "kata Seneca, capek sering muncul bukan karena lemah, tapi karena terlalu lama nahan",
        "Seneca juga pernah bilang, kadang yang bikin capek itu bukan kerjaannya, tapi pikiran yang nggak istirahat",
        "filsuf Stoik percaya, berhenti sebentar itu bukan menyerah",
        "capek kadang tanda kamu udah bertahan cukup lama",
        "nggak semua capek harus langsung diselesaikan",
        "Stoik melihat istirahat sebagai bagian dari bertahan",
        "kadang berhenti justru bikin jalan lebih jauh",
        "capek bukan tanda gagal, tapi tanda kamu udah jalan jauh",
        "menarik napas juga termasuk bergerak",
        "nggak semua hal harus diberesin hari ini",
        "Seneca pernah mengingatkan bahwa kelelahan sering datang dari pikiran yang tak pernah pulang",
        "bagi Stoik, menjaga diri adalah bagian dari tanggung jawab",
        "capek kadang bukan karena kurang kuat, tapi karena terlalu lama menahan",
        "berhenti sebentar bukan pengkhianatan terhadap tujuan",
        "istirahat bukan lawan dari ketekunan",
        "Seneca menulis bahwa hidup bukan untuk dijalani sambil terseret",
        "capek adalah sinyal, bukan vonis",
        "tubuh dan pikiran punya batas yang perlu dihormati",
        "bertahan tanpa jeda justru memperpendek jarak",
        "capek bisa jadi undangan untuk merawat diri",

        "Stoik tidak memuja penderitaan",
        "mereka percaya keseimbangan lebih bernilai daripada heroisme kosong",
        "capek adalah bahasa tubuh yang jujur",
        "kadang yang perlu diperbaiki bukan dirimu, tapi ritmenya",
        "menurunkan tempo bukan berarti kalah",
        "istirahat juga keputusan rasional",
        "capek yang diakui lebih cepat reda",
        "Seneca menulis: tidak semua hari harus ditaklukkan",
        "bernapas adalah bentuk perlawanan paling lembut",
        "capek mengingatkan bahwa kamu manusia, bukan mesin",

        "Stoik memandang hidup sebagai maraton, bukan sprint",
        "kelelahan sering muncul saat kita lupa tujuan awal",
        "capek bukan musuh, tapi penunjuk arah",
        "kadang tubuh lebih bijak dari ambisi",
        "memperlambat langkah bisa menyelamatkan perjalanan",
        "capek menandai bahwa kamu sudah berjalan jauh",
        "istirahat memberi ruang untuk pulih",
        "menjaga diri bukan bentuk egoisme",
        "capek tidak menghapus nilai usahamu",
        "hari berat tetap bagian dari hidup yang utuh",
        "Seneca menulis bahwa hidup terasa berat saat kita lupa berhenti sejenak",

    "capek bukan tanda kamu kalah, tapi tanda kamu sudah berjalan jauh",
    "Stoik percaya bahwa menjaga diri adalah bentuk kebijaksanaan",
    "capek sering muncul saat kita memikul beban sendirian",
    "tidak semua perjuangan harus terlihat",
    "kadang yang paling berani adalah mengakui lelah",
    "istirahat memberi ruang bagi kejernihan",
    "capek tidak menghapus makna usaha",
    "menurunkan tempo bukan berarti menyerah",
    "Stoik memandang keseimbangan lebih penting dari paksaan",

    "capek adalah bahasa tubuh yang jujur",
    "pikiran yang lelah butuh ketenangan, bukan dorongan",
    "Seneca mengingatkan bahwa waktu juga bagian dari obat",
    "capek mengajarkan batas yang sehat",
    "bertahan tanpa jeda bukan kebajikan",
    "kadang diam adalah bentuk perlindungan",
    "capek bisa menjadi titik evaluasi",
    "tidak semua hari harus produktif",
    "Stoik tidak memuja penderitaan",
    "capek mengingatkan bahwa kamu manusia",

    "menjaga diri bukan pengkhianatan terhadap tanggung jawab",
    "capek menunjukkan kamu masih peduli",
    "kadang yang perlu dilepas bukan tujuan, tapi caranya",
    "Seneca percaya hidup yang baik bukan hidup yang diperas",
    "capek memberi sinyal untuk merawat diri",
    "istirahat tidak mengurangi nilai dirimu",
    "capek adalah bagian dari ritme hidup",
    "Stoik percaya keseimbangan melahirkan ketahanan",
    "capek tidak perlu dibuktikan",
    "menghormati lelah adalah bentuk kebijaksanaan",

    "kadang cukup berhenti tanpa alasan",
    "lelah tidak perlu pembelaan",
    "bertahan juga butuh jeda",
    "capek bukan musuh",
    "diam juga bentuk gerak",
    "mengurangi beban itu sah",
    "tidak semua harus dituntaskan",
    "menarik napas juga usaha",
    "capek tidak menghapus niat baik",
    "istirahat bukan kemunduran",

    "capek boleh diakui",
    "tidak apa-apa melambat",
    "berhenti bukan gagal",
    "capek tidak perlu disembunyikan",
    "ritme hidup tidak selalu cepat",
    "lelah adalah sinyal",
    "menghormati tubuh itu bijak",
    "capek bukan aib",
    "tenang juga produktif",
    "cukup itu relatif",

    "tidak semua hari harus kuat",
    "lelah tidak mendefinisikanmu",
    "capek datang dan pergi",
    "hari berat bukan hukuman",
    "melambat itu manusiawi",
    "capek bisa dirawat",
    "menjaga diri itu perlu",
    "tidak semua bisa dikontrol",
    "capek bukan akhir",
    "esok masih ada",

    "capek muncul saat batas dilewati",
    "batas bukan kelemahan",
    "menjaga diri itu keputusan sadar",
    "lelah tidak meniadakan niat baik",
    "hidup tidak lomba sprint",
    "tidak semua harus maksimal",
    "cukup juga pencapaian",
    "capek mengingatkan untuk merawat",
    "tenang itu kebutuhan",
    "berhenti sejenak tidak menghapus tujuan",

    "capek sering datang sebelum sadar diri",
    "mendengar tubuh itu kebijaksanaan",
    "tidak semua hari harus produktif",
    "lelah bukan kegagalan sistem",
    "manusia punya kapasitas",
    "melampaui batas ada harganya",
    "capek mengajak memperlambat",
    "istirahat menyelamatkan banyak hal",
    "lelah tidak harus dibuktikan",
    "capek boleh diakui diam-diam",

    "capek tidak butuh pembenaran",
    "tidak semua bisa ditanggung sendiri",
    "membagi beban itu sah",
    "capek tidak mengurangi nilai",
    "bertahan lama memang melelahkan",
    "pelan menjaga konsistensi",
    "bernapas juga usaha sadar",
    "capek tidak perlu disangkal",
    "menjaga energi itu strategi",
    "hidup bukan soal habis-habisan",

    "capek tidak butuh izin",
    "lelah bukan dosa",
    "berhenti juga pilihan sadar",
    "energi itu terbatas",
    "tidak semua harus selesai",
    "cukup hari ini sudah cukup",
    "capek mengingatkan batas",
    "batas menjaga kelangsungan",
    "menjaga diri bukan egois",
    "istirahat bukan kemunduran",

    "capek muncul sebelum sadar",
    "lelah minta diperhatikan",
    "diam kadang paling jujur",
    "pelan menjaga napas",
    "menunda bukan gagal",
    "lelah tidak menghapus niat",
    "capek tidak memalukan",
    "tubuh tahu kapan berhenti",
    "pikiran juga bisa lelah",
    "bernapas itu perlu",

    "capek tidak harus dibuktikan",
    "tidak semua orang harus tahu",
    "cukup untuk hari ini",
    "besok bisa dilanjutkan",
    "capek tidak mengurangi nilai",
    "bertahan lama itu berat",
    "lelah tidak perlu dilawan",
    "menjaga tenaga itu bijak",
    "hidup bukan soal kuat terus",
    "rapuh juga manusiawi"
    ],

    "sedih": [
        "kata Epictetus, nggak semua hal harus dilawan—kadang diterima dulu",
        "Epictetus percaya perasaan datang untuk dilewati, bukan diusir",
        "sedih bukan tanda gagal, sering kali tanda peduli",
        "Stoik nggak ngajarin kebal, tapi sadar batas kendali",
        "nggak apa-apa ngerasa sedih tanpa harus buru-buru kuat",
        "Marcus Aurelius menulis, hati yang terluka tetap layak dirawat",
        "sedih itu bagian dari jadi manusia",
        "kadang perasaan perlu diakui sebelum reda",
        "nggak semua luka harus langsung sembuh",
        "menerima bukan berarti menyerah",
        "Epictetus mengingatkan bahwa perasaan tidak perlu dilawan",
        "sedih bukan kegagalan pengendalian diri",
        "Stoik membedakan antara merasakan dan tenggelam",
        "mengakui sedih adalah bentuk kejujuran",
        "Marcus Aurelius menulis bahwa hati juga perlu dirawat",
        "sedih menunjukkan adanya keterikatan yang bermakna",
        "tidak semua luka harus disembunyikan",
        "sedih adalah bagian dari relasi dengan dunia",
        "perasaan tidak membuatmu lemah",
        "sedih memberi sinyal tentang apa yang penting",

        "Stoik tidak menolak emosi, mereka menolak dikuasai emosi",
        "menerima sedih bukan berarti menyerah",
        "kadang kesedihan perlu duduk dulu sebelum pergi",
        "sedih mengajarkan batas kendali",
        "Marcus menulis: jangan tambah penderitaan dengan perlawanan",
        "sedih bisa menjadi ruang refleksi",
        "menangis bukan kegagalan karakter",
        "kesedihan tidak menghapus martabat",
        "perasaan datang dan pergi seperti cuaca",
        "sedih tidak harus diselesaikan hari ini",

        "Stoik percaya ketenangan lahir dari penerimaan",
        "sedih adalah reaksi alami atas kehilangan",
        "tidak semua kehilangan bisa dipercepat penyembuhannya",
        "sedih mengingatkan bahwa kamu peduli",
        "mengizinkan sedih justru mempercepat pulih",
        "Marcus menulis bahwa hati yang lembut bukan kelemahan",
        "sedih tidak perlu pembenaran",
        "perasaan tidak menuntut solusi instan",
        "sedih layak mendapat ruang",
        "menjadi manusia berarti bisa terluka",

        "Epictetus mengajarkan bahwa perasaan tidak bisa dilarang, hanya dipahami",
    "sedih bukan kegagalan karakter",
    "Stoik tidak menuntut hati menjadi batu",
    "sedih adalah reaksi wajar atas kehilangan",
    "Marcus Aurelius menulis bahwa hati yang terluka tetap layak dirawat",
    "sedih tidak perlu disangkal untuk menjadi kuat",
    "perasaan hadir untuk dilewati, bukan diusir",
    "sedih memberi ruang untuk mengenal diri",
    "tidak semua luka perlu segera sembuh",
    "menerima sedih adalah bentuk kejujuran",

    "Stoik membedakan antara merasakan dan tenggelam",
    "sedih tidak membuatmu lemah",
    "kadang kesedihan hanya minta ditemani",
    "Marcus menulis: jangan tambah beban dengan perlawanan",
    "sedih mengajarkan batas kendali",
    "mengizinkan sedih justru mempercepat pulih",
    "sedih adalah bagian dari hidup yang utuh",
    "perasaan tidak menuntut solusi cepat",
    "sedih bukan musuh rasionalitas",
    "kesedihan tidak menghapus martabat",

    "Stoik percaya ketenangan lahir dari penerimaan",
    "sedih menandakan adanya nilai",
    "kehilangan wajar melahirkan duka",
    "sedih tidak perlu alasan logis",
    "Marcus percaya hati yang lembut bukan kelemahan",
    "sedih boleh ada tanpa harus diperbaiki",
    "perasaan datang dan pergi seperti cuaca",
    "sedih tidak menentukan siapa dirimu",
    "mengakui sedih adalah bentuk keberanian",
    "menjadi manusia berarti bisa terluka",

    "sedih tidak butuh izin",
    "perasaan tidak salah",
    "sedih tidak merusak nilai diri",
    "menangis juga bentuk lega",
    "sedih tidak selalu butuh solusi",
    "hati tidak harus kuat terus",
    "sedih datang tanpa jadwal",
    "diam kadang lebih jujur",
    "sedih bukan tanda kalah",
    "perasaan tidak perlu dibenarkan",

    "sedih boleh hadir",
    "tidak apa-apa merasa",
    "hati punya waktunya sendiri",
    "sedih tidak permanen",
    "menahan sedih justru melelahkan",
    "perasaan ingin dipahami",
    "sedih tidak harus dijelaskan",
    "menjadi rapuh itu manusiawi",
    "sedih tidak mengurangi martabat",
    "perlahan juga proses",

    "sedih tidak membuatmu kecil",
    "hati butuh ruang",
    "perasaan bukan musuh",
    "sedih tidak meniadakan harapan",
    "tidak semua luka terlihat",
    "hati tidak harus kebal",
    "sedih tidak perlu dipercepat",
    "waktu membantu tanpa dipaksa",
    "sedih adalah bagian hidup",
    "hidup tidak selalu ringan",

    "sedih tidak meminta izin",
    "hati bereaksi sebelum logika",
    "perasaan tidak selalu rasional",
    "sedih tidak perlu diluruskan",
    "merasakan bukan kesalahan",
    "sedih tidak menghapus kekuatan",
    "air mata tidak melemahkan",
    "hati punya bahasanya sendiri",
    "sedih tidak harus dijelaskan",
    "perasaan tidak menunggu kesiapan",

    "sedih sering muncul dari kepedulian",
    "kehilangan selalu meninggalkan jejak",
    "hati butuh waktu mencerna",
    "sedih tidak bisa dipaksa pergi",
    "mengizinkan sedih itu merawat",
    "menahan sedih memperpanjang luka",
    "sedih tidak mengurangi harga diri",
    "diam bisa jadi bentuk hormat",
    "sedih bukan tanda rusak",
    "hati tidak perlu disalahkan",

    "sedih hadir tanpa niat jahat",
    "perasaan datang untuk dilewati",
    "sedih tidak perlu dilawan",
    "menerima membuka ruang lega",
    "hati pulih perlahan",
    "sedih tidak permanen",
    "rasa datang dan pergi",
    "hati tahu ritmenya",
    "sedih tidak menghalangi hidup",
    "hidup tetap berjalan pelan",

     "sedih tidak perlu alasan",
    "hati bereaksi lebih cepat",
    "perasaan tidak menunggu logika",
    "sedih tidak salah",
    "menangis tidak gagal",
    "hati punya waktunya",
    "sedih tidak minta solusi",
    "cukup ditemani",
    "diam juga bentuk hadir",
    "hati butuh ruang",

    "sedih tidak selalu keras",
    "kadang ia sunyi",
    "kadang ia pelan",
    "perasaan datang bergelombang",
    "tidak perlu dipercepat",
    "sedih tidak perlu diluruskan",
    "merasakan itu sehat",
    "menahan memperpanjang",
    "mengakui membuka",
    "hati pulih pelan",

    "sedih tidak menghapus harapan",
    "luka tidak permanen",
    "perasaan berubah",
    "hari buruk tidak abadi",
    "sedih tidak menelan hidup",
    "ia hanya singgah",
    "hati belajar dari rasa",
    "perasaan tidak musuh",
    "sedih bagian perjalanan",
    "hidup tetap bergerak"
    ],

    "bingung": [
        "kata Marcus Aurelius, nggak apa-apa belum nemu jawaban hari ini",
        "kejernihan sering datang setelah kebingungan",
        "bingung sering muncul sebelum sesuatu jadi jelas",
        "nggak semua keputusan harus selesai sekarang",
        "kadang bingung cuma tanda kamu lagi mikir serius",
        "Stoik percaya waktu membantu memilah yang penting",
        "bingung bukan tanda gagal berpikir",
        "kadang pikiran butuh diam sebelum jelas",
        "pelan bukan berarti mundur",
        "waktu sering memberi jarak yang menenangkan",
        "Marcus Aurelius menulis bahwa kebingungan mendahului kejernihan",
        "bingung bukan tanda kegagalan berpikir",
        "Stoik melihat keraguan sebagai bagian dari penilaian",
        "tidak semua jawaban muncul sekaligus",
        "bingung menandakan proses sedang berjalan",
        "ketidakpastian adalah kondisi manusiawi",
        "waktu sering memberi jarak yang membantu",
        "bingung adalah jeda sebelum keputusan matang",
        "tidak semua pilihan harus segera diputuskan",
        "pelan bukan berarti salah arah",

        "Stoik percaya bahwa kejelasan datang dari ketenangan",
        "bingung muncul saat banyak nilai saling bertabrakan",
        "tidak semua hal bisa dipahami sekarang",
        "bingung menandakan kamu sedang mempertimbangkan",
        "Marcus menulis: bersabarlah dengan pikiranmu",
        "kebingungan bukan musuh rasio",
        "kadang diam lebih membantu daripada memaksa jawaban",
        "bingung memberi waktu untuk menyaring",
        "tidak ada keharusan untuk selalu yakin",
        "berpikir pelan sering lebih jujur",

        "Stoik tidak terburu-buru menyimpulkan",
        "bingung adalah fase, bukan identitas",
        "ketidakpastian tidak selalu berbahaya",
        "bingung membuka ruang belajar",
        "tidak semua jalan harus jelas dari awal",
        "Marcus percaya bahwa arah terbentuk sambil berjalan",
        "bingung memberi kesempatan untuk refleksi",
        "keputusan matang butuh waktu",
        "bingung bukan kelemahan intelektual",
        "manusia tidak diciptakan untuk selalu tahu",

        "Marcus Aurelius menulis bahwa kejernihan sering datang setelah kebingungan",
    "bingung bukan tanda kegagalan berpikir",
    "Stoik melihat keraguan sebagai bagian dari pertimbangan",
    "tidak semua jawaban harus muncul sekarang",
    "bingung menandakan kamu sedang memproses",
    "ketidakpastian adalah kondisi manusiawi",
    "waktu memberi jarak yang menenangkan",
    "bingung adalah jeda sebelum keputusan matang",
    "tidak semua pilihan harus segera diputuskan",
    "pelan bukan berarti salah arah",

    "Stoik percaya ketenangan mendahului kejelasan",
    "bingung muncul saat nilai saling bertabrakan",
    "tidak semua hal bisa dipahami sekaligus",
    "bingung menandakan kehati-hatian",
    "Marcus menulis: bersabarlah dengan pikiranmu",
    "kebingungan bukan musuh rasio",
    "kadang diam membantu lebih dari memaksa jawaban",
    "bingung memberi waktu untuk menyaring",
    "tidak ada kewajiban untuk selalu yakin",
    "berpikir pelan sering lebih jujur",

    "Stoik tidak tergesa dalam menyimpulkan",
    "bingung adalah fase, bukan identitas",
    "ketidakpastian tidak selalu berbahaya",
    "bingung membuka ruang belajar",
    "tidak semua jalan harus jelas sejak awal",
    "Marcus percaya arah terbentuk sambil berjalan",
    "bingung memberi kesempatan refleksi",
    "keputusan matang butuh waktu",
    "bingung bukan kelemahan intelektual",
    "manusia tidak diciptakan untuk selalu tahu",

    "bingung bukan kesalahan",
    "tidak tahu itu wajar",
    "pikiran butuh waktu",
    "jawaban tidak selalu cepat",
    "bingung tidak memalukan",
    "ragu bukan kelemahan",
    "bingung tanda berpikir",
    "tidak semua jelas sekarang",
    "pelan bukan salah arah",
    "bingung juga fase",

    "tidak harus yakin hari ini",
    "bingung memberi jeda",
    "pikiran tidak mesin",
    "bingung membuka kemungkinan",
    "ragu tanda peduli",
    "kejelasan datang bertahap",
    "bingung tidak berbahaya",
    "berpikir pelan itu sah",
    "bingung bukan buntu",
    "arah bisa dibentuk",

    "bingung tidak menghapus niat",
    "ketidakpastian itu normal",
    "jawaban bisa menunggu",
    "bingung memberi ruang refleksi",
    "tidak semua harus pasti",
    "bingung tidak meniadakan nilai",
    "pikiran juga lelah",
    "diam membantu fokus",
    "bingung tidak menentukan akhir",
    "jalan tidak selalu lurus",

    "bingung muncul saat peduli",
    "ketidakpastian bagian berpikir",
    "tidak tahu itu jujur",
    "bingung bukan tanda kosong",
    "pikiran butuh waktu menyusun",
    "jawaban tidak selalu instan",
    "bingung memberi jarak refleksi",
    "tidak semua jelas sekaligus",
    "bingung membuka kemungkinan",
    "ragu tidak selalu buruk",

    "bingung sering sebelum paham",
    "ketidakjelasan bukan kegagalan",
    "pikiran bekerja di balik layar",
    "diam membantu memilah",
    "bingung mengajarkan kesabaran",
    "tidak semua harus diputuskan",
    "waktu membantu kejernihan",
    "bingung bukan jalan buntu",
    "arah bisa berubah",
    "fleksibel itu bertahan",

    "bingung tidak menghapus tujuan",
    "jawaban bisa menunggu",
    "ketidakpastian bukan ancaman",
    "bingung tanda refleksi",
    "pikiran juga punya lelah",
    "memikirkan hidup itu berat",
    "bingung tidak memalukan",
    "bertanya itu sehat",
    "bingung tidak mendefinisikan akhir",
    "jalan terbentuk sambil berjalan",

     "bingung tanda peduli",
    "tidak tahu itu jujur",
    "ragu bagian berpikir",
    "jawaban tidak selalu cepat",
    "bingung membuka ruang",
    "pikiran menyusun pelan",
    "diam membantu jelas",
    "tidak semua pasti",
    "ketidakpastian wajar",
    "bingung bukan gagal",

    "pikiran butuh waktu",
    "jawaban bisa menunggu",
    "bingung bukan akhir",
    "jalan terbentuk sambil jalan",
    "ragu menjaga kehati-hatian",
    "bingung mencegah gegabah",
    "tidak jelas bukan salah",
    "bertanya itu sehat",
    "bingung tidak memalukan",
    "mencari itu hidup",

    "bingung tidak menghapus tujuan",
    "arah bisa berubah",
    "rencana boleh bergeser",
    "fleksibel itu bertahan",
    "bingung tanda refleksi",
    "pikiran juga lelah",
    "berhenti mikir sejenak sah",
    "kejernihan datang belakangan",
    "bingung mendahului paham",
    "waktu membantu memilah"
    ]
}


# ======================
# MICRO RESPONSES (OPSIONAL)
# ======================

MICRO_RESPONSES = [
    "Hmm, iya.",
    "Aku ngerti.",
    "Berat ya.",
    "Masuk akal.",
    "Aku denger.",
    "Iya, lanjut.",
    "Pelan aja.",
    "Kerasa.",
    "Aku ikut.",
    "Hmm.",

    "Iya.",
    "Aku masih di sini.",
    "Aku nangkep.",
    "Aku paham.",
    "Iya, aku denger.",
    "Aku temenin.",
    "Berasa berat.",
    "Hmm, berat.",
    "Iya, pelan.",
    "Aku ada.",

    "Aku nyimak.",
    "Aku nggak ke mana-mana.",
    "Aku hadir.",
    "Aku ikutin.",
    "Kerasa capeknya.",
    "Iya, aku ngerti.",
    "Hmm, iya.",
    "Aku dengerin.",
    "Pelan.",
    "Iya, aman.",

    "Iya, kerasa.",
    "Hmm, iya ya.",
    "Berat sih.",
    "Aku ngerti kenapa.",
    "Masuk akal banget.",
    "Iya, wajar.",
    "Aku nangkep maksudmu.",
    "Iya, lanjut.",
    "Hmm…",
    "Aku masih nyimak.",

    "Iya, itu berat.",
    "Aku denger kok.",
    "Pelan aja.",
    "Iya, nggak gampang.",
    "Aku paham rasanya.",
    "Iya, masuk akal.",
    "Aku ikut ngerasain.",
    "Hmm, berat banget.",
    "Iya, aku di sini.",
    "Aku temenin ya.",

    "Kerasa capeknya.",
    "Iya, itu nyentuh.",
    "Aku ngerti.",
    "Hmm, iya.",
    "Iya, aku dengerin.",
    "Aku hadir.",
    "Iya, pelan.",
    "Aku nggak ke mana-mana.",
    "Hmm, aku nangkep.",
    "Aku ikut alurnya."
]


# ======================
# FORBIDDEN PHRASES
# ======================

FORBIDDEN_PHRASES = [
    "sebagai asisten",
    "saya hanyalah",
    "menurut sistem",
    "pengguna",
    "pengalaman pengguna",
    "secara umum",
    "dalam konteks ini",
    "secara teoritis",
    "berdasarkan data",
    "optimalisasi",

    "sebaiknya anda",
    "anda perlu",
    "anda harus",
    "solusi terbaik adalah",
    "langkah-langkah",
    "panduan berikut",
    "kesimpulannya",
    "dapat disimpulkan",

    "dalam hal ini",
    "oleh karena itu",
    "sebaiknya dilakukan",
    "disarankan untuk",
    "berdasarkan penelitian",
    "menurut teori",
    "secara logis",
    "secara rasional",
    "analisis menunjukkan",
    "hasil menunjukkan",

    "langkah pertama",
    "langkah kedua",
    "kesimpulan akhir",
    "secara sistematis",
    "optimal",
    "efisiensi",
    "implementasi",
    "parameter",
    "indikator",
    "evaluasi",

    "secara umum",
    "pada dasarnya",
    "hal ini menunjukkan",
    "dapat disimpulkan",
    "dapat dikatakan",
    "merupakan suatu",
    "bertujuan untuk",
    "dalam konteks ini",
    "dengan demikian",
    "oleh sebab itu",

    "disarankan agar",
    "perlu dipertimbangkan",
    "perlu diperhatikan",
    "perlu diketahui",
    "perlu diingat",
    "secara konseptual",
    "secara teoritis",
    "berdasarkan konsep",
    "menurut pendekatan",
    "berdasarkan pendekatan"
]

CONTINUATION_RESPONSES = [
    "Terus gimana setelah itu?",
    "Abis itu apa yang kamu rasain?",
    "Bagian ini pengin kamu ceritain lebih?",
    "Terus apa yang bikin kamu bertahan?",
    "Lalu apa yang paling kerasa?",
    "Terus kamu ngadepinnya gimana?",
    "Abis itu kejadiannya ke mana arahnya?",
    "Terus apa yang berubah?",
    "Bagian ini penting ya buat kamu.",
    "Terus apa yang bikin kamu diem?",

    "Kalau lanjut, ceritanya ke mana?",
    "Bagian ini yang paling berat?",
    "Terus apa yang bikin kamu mikir?",
    "Setelah itu rasanya gimana?",
    "Bagian ini bikin kamu capek ya.",
    "Terus apa yang belum selesai?",
    "Kalau dilanjutin, apa yang muncul?",
    "Bagian ini yang paling nyangkut?",
    "Terus kamu ngerasain apa?",
    "Aku masih ngikutin."
]

VALIDATION_RESPONSES = [
    "Perasaan itu masuk akal.",
    "Wajar kalau ini terasa berat.",
    "Ngerasa kayak gini nggak salah.",
    "Reaksi kamu manusiawi.",
    "Dengan situasi kayak gitu, wajar capek.",
    "Nggak aneh kalau kamu ngerasa begitu.",
    "Perasaan ini valid.",
    "Masuk akal kalau kamu ngerasa lelah.",
    "Nggak berlebihan ngerasa kayak gini.",
    "Kamu nggak lebay.",

    "Apa yang kamu rasain ada alasannya.",
    "Ngerasa kayak gini bukan kelemahan.",
    "Itu respon yang wajar.",
    "Nggak salah ngerasa seperti ini.",
    "Kamu nggak rusak.",
    "Kamu masih manusia.",
    "Perasaan ini punya tempat.",
    "Kamu nggak salah jalan.",
    "Ini berat, dan itu nyata.",
    "Kamu nggak sendirian ngerasain ini."
]


# ======================
# UTIL
# ======================

def clean_response(text: str) -> str:
    if not text:
        return ""
    t = text.lower()
    if any(bad in t for bad in FORBIDDEN_PHRASES):
        return ""
    if len(text.split()) > 80:
        return ""
    return text.strip()


def is_greeting(text: str) -> bool:
    return text.lower().strip() in ["halo", "hai", "hi", "hey", "p"]


def detect_emotion(text: str) -> str:
    t = text.lower()
    if "capek" in t or "lelah" in t:
        return "capek"
    if "sedih" in t or "kecewa" in t:
        return "sedih"
    if "bingung" in t or "nggak tau" in t:
        return "bingung"
    return "netral"


def is_concrete_story(text: str) -> bool:
    t = text.lower()
    return any(k in t for k in ["tugas", "kerjaan", "kantor", "dia", "orang"])


# ======================
# ROUTES
# ======================

@app.get("/", response_class=HTMLResponse)
def serve_ui():
    with open("static/index.html", encoding="utf-8") as f:
        return f.read()


@app.post("/chat")
def chat(req: ChatRequest):
    user_text = req.message.strip()

    if not user_text or is_greeting(user_text):
        return JSONResponse({"reply": random.choice(PURE_GREETINGS)})

    if check_risk(user_text):
        return JSONResponse({"reply": CRISIS_MESSAGE})

    emotion = detect_emotion(user_text)
    concrete = is_concrete_story(user_text)

    empathy = random.choice(EMPATHY_BANK.get(emotion, EMPATHY_BANK["netral"]))
    philosophy = ""

    if emotion != "netral" and not concrete:
        philosophy = random.choice(PHILOSOPHY_BANK.get(emotion, []))

    prompt = f"""
{BASE_PERSONA}

ATURAN:
- Jangan mengarang
- Jangan sok ngerti
- Bahasa ngobrol, singkat, jelas

Pesan pengguna:
{user_text}

Balasan:
""".strip()

    try:
        response = requests.post(
            GROQ_URL,
            headers={
                "Authorization": f"Bearer {GROQ_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "model": MODEL_NAME,
                "messages": [
                    {"role": "system", "content": BASE_PERSONA},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.3,
                "top_p": 0.85,
                "max_tokens": 350
            },
            timeout=60
        )

        if response.status_code != 200:
            print("GROQ ERROR:", response.text)
            raise ValueError("Groq request failed")

        data = response.json()
        raw = data["choices"][0]["message"]["content"].strip()
        core = clean_response(raw)

        if not core:
            core = random.choice(SAFE_FALLBACK)

    except Exception:
        traceback.print_exc()
        core = random.choice(SAFE_FALLBACK)

    final_reply = " ".join(
        part for part in [empathy, philosophy, core] if part
    )

    return JSONResponse({"reply": final_reply})
